name: devop
on:
  push:
    branches: ['main']
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: ${{secrets.GCP_SSH_PRIVATE_KEY}}
        host: ${{secrets.HOST}}
        username: ${{secrets.SSH_USER}}
