name: devop
on:
  push:
    branches: ['main']
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # - name: Checkout
      #   uses: actions/checkout/@v2

      # - name: Login Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx
      # - name: build and push
      #   uses: docker/build-push-action@v2
      #   id: docker_build
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/devop

      # - name: verify
      #   run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/weighty-droplet-357309/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'abeesdevop@weighty-droplet-357309.iam.gserviceaccount.com '

      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'abeesdevop'
          zone: 'asia-southeast1-b'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: 'echo Hello world'
